### ISSUE TITLE
Installation in integration

### ISSUE THREAD

**Issue by jfmeuniercow** [pinkywafer/Calendarific#49]
Good morning to all of you.

I just installed the software. However, when I go to the integration to install it, here's what I have:

_No holidays found. Ensure that you have configured Calendarific with a valid country and api key. [Please read the instructions](https://github.com/pinkywafer/Calendarific)."_ 

However, I have configured the configuration.yaml file:

```
# Configure a default setup of Home Assistant (frontend, api, etc)

calendarific:
  api_key: AEOqZQtdcf...
  country: ca
  
sensor:
  - platform: calendarific
    holiday: New Year's Day
  - platform: calendarific
    holiday: Christmas Day
```

Can you help me?

Thanks
